# Generated by Django 5.2.4 on 2025-08-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='studentresponse',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='exams', to='exam_system.question'),
        ),
    ]
